language: node_js
node_js:
  - "node"

sudo: required
services:
  - docker

script:
  # set docker variables for arango
  - docker run -d -e "ARANGODB_USERNAME=t" -e "ARANGODB_PASSWORD=t" -e "ARANGODB_DB=t" arangodb
  # set node env variables
  - ARANGODB_DB=t ARANGODB_USERNAME=t ARANGODB_PASSWORD=t npm test