#The dockerfile for Wikilogic's API node server

# Pull base image - we're running it on Ubuntu!
FROM node

WORKDIR /var/www/api/
#copy the package.json & install
COPY ./package.json package.json
RUN npm install
RUN npm install nodemon -g

# Define default command.
CMD ["nodemon", "api-server.js", "-L"]

VOLUME ["/var/www/api/api-server.js", "/var/www/api/read", "/var/www/api/write", "/var/www/api/neo4j"]

# Expose ports.
EXPOSE 3030