# This is a compose file intended for testing the API in Travic CIversion: '3'
services:
  api:
    build: .
    environment:
    - ARANGODB_HOST=arango
    - ARANGODB_PORT=8529
    - ARANGODB_USERNAME=t
    - ARANGODB_PASSWORD=t
    - ARANGODB_DB=t
    ports:
    - "3030:3030"
  arango:
    image: arangodb/arangodb:3.2.2
    ports:
    - "8529:8529"
    environment:
    # - ARANGO_ROOT_PASSWORD=t
    - ARANGODB_USERNAME=t
    - ARANGODB_PASSWORD=t
    - ARANGODB_DB=t