#The dockerfile for Wikilogic's API node server

# Pull base image - we're running it on Ubuntu!
FROM node

WORKDIR /var/www/api/
#copy the package.json & install
COPY ./package.json package.json
RUN npm install
RUN npm install nodemon -g

# Define default command.
CMD ["nodemon", "api-server.js"]

# Expose ports.
EXPOSE 3030