#The dockerfile for Wikilogic's API node server

# Pull base image - we're running it on Ubuntu!
FROM node

WORKDIR /var/www/api/
#copy the package.json & install
COPY ./package.json package.json
COPY ./node_modules /var/www/api/node_modules
# RUN npm install COPYing node_modules to cut down on docker build time
RUN npm install nodemon -g

COPY ./guestlist.js guestlist.js

# Define default command.
CMD ["nodemon", "api-server.js", "-L"]

VOLUME ["/var/www/api/api-server.js", "/var/www/api/src"]

# Expose ports.
EXPOSE 3030